# Generated by Django 5.2.1 on 2025-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0008_rename_post_artikelblog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikelblog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artikelblog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='artikelblog',
            name='isi',
        ),
        migrations.AddField(
            model_name='artikelblog',
            name='konten',
            field=models.TextField(blank=True, null=True),
        ),
    ]
