# Generated by Django 5.2.1 on 2025-06-14 12:28

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0012_komentar_created_at_komentar_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='artikelblog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='artikelblog',
            name='konten',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
